### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by jashshah** [mesuvash/NNRec#2]
Hi,

While running the `autorec` code for my own custom data I'm getting the following error: `ValueError: too many values to unpack`. What do you think can be done? 

The complete error:

```
Traceback (most recent call last):                         ]   0% ETA:  --:--:--
  File "learner.py", line 58, in <module>
    train(config_path)
  File "learner.py", line 20, in train
    shape=shape)
  File "/home/soumendra/NNRec/dataUtils/data.py", line 103, in loadTrainTest
    d.import_ratings(train_path, shape)
  File "/home/soumendra/NNRec/dataUtils/data.py", line 37, in import_ratings
    userid, itemid, rating = line.split()
ValueError: too many values to unpack
```

I can send you the data if you'd like.

**Comment by mesuvash** [comment]
This generally happens when one provides incorrect train/test file path in the configuration file. Could you please confirm that?

**Comment by Gunther17** [comment]
hello, 
num_lines = int(r.std_out.strip().partition(' ')[0])
ValueError: invalid literal for int() with base 10: ''

**Comment by mesuvash** [comment]
Hi Gunther,

Can you check the output of (r.std_out.strip().partition(' ') ?

-Suvash
